name: CD - Build & Publish Images

on:
  push:
    branches: [ "main" ]
    tags:     [ "v*" ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write        # pour GHCR
      id-token: write        # (utile si tu signes plus tard)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # 1) Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2) Login GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3) Métadonnées (tags/labels)
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/sysinfo-api
            ghcr.io/${{ github.repository_owner }}/sysinfo-api
          tags: |
            # -> si push de tag 'vX.Y.Z', on fabrique 'X.Y.Z'
            type=semver,pattern={{version}},value=${{ github.ref_name }}
            # -> 'latest' uniquement sur main
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # -> tag de secours par SHA
            type=sha

      # 4) Build & Push
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
